# Generated by Django 4.2.16 on 2024-10-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplefield', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
